require("plugin.oil")
require("plugin.telescope")
require("plugin.undotree")
require("plugin.harpoon")
require("plugin.lsp-zero-v4")
require("plugin.treesitter")
--require("plugin.ultimate-autopair")
